language: python

python:
    - 2.6
    - 2.7
    - pypy
#    - 3.2

script: python setup.py nosetests --tests=importtools.importables,importtools.datasets

notifications:
  email:
      - banesiu.sever@gmail.com
